# Generated by Django 5.2.5 on 2025-09-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='token_type',
            field=models.CharField(choices=[('PASSWORD_RESET', 'Password Reset')], default='PASSWORD_RESET', max_length=50),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=25),
        ),
    ]
