# Generated by Django 5.2.5 on 2025-09-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_token_token_type_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token_type',
            field=models.CharField(choices=[('PASSWORD_RESET', 'Password Reset')], max_length=50),
        ),
    ]
