# Generated by Django 5.2.5 on 2025-09-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_token_token_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token_type',
            field=models.CharField(choices=[('PASSWORD_RESET', 'Password Reset')], default='PASSWORD_RESET', max_length=50),
        ),
    ]
